version: '3.8'

# Описание контейнеров которые будут запущены
services:
  mongo:
    image: mongo:6
    container_name: app-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  api:
    build: ./api
    container_name: app-backend
    ports:
      - '8000:8000'
    env_file:
      - ./api/.env
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./uploads/images:/app/public/images

  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    restart: always

  puppeteer-test:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    container_name: puppeteer-test
    command: ["npm", "run", "codeceptjs:headless"]
    env_file:
      - ./tests/.env.test
    depends_on:
      - frontend
      - api
    profiles: ["test"]
    shm_size: '2gb'  # важно для работы headless Chrome
volumes:
  mongo_data: