version: '3.8'

# Описание контейнеров которые будут запущены
services:
  mongo:
    image: mongo:6
    container_name: app-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: app-backend
    ports:
      - '8000:8000'
    env_file:
      - ./api/.env
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    restart: always

volumes:
  mongo_data: