name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  test:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
  
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'
  
        - name: Install dependencies in /api
          working-directory: ./api
          run: npm ci
  
        - name: Run tests
          working-directory: ./api
          run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            cd shop-js-27
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
